# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo cp test.sh.example test.sh
    sudo chmod 0700 test.sh
    sudo ./test.sh
  displayName: 'Test build script'
